-- ============================================================
-- 心屿 MindIsle v5 · Supabase 初始化迁移 001_init.sql
-- 内容：
--   1) 9 张业务表（字段严格按需求，含默认值/外键/索引/CHECK）
--   2) 行级安全 RLS：四角色策略（学生/家长/学校/社区）
--   3) 匿名聚合视图（学校端本校口径 / 社区端区域口径 / 树洞匿名流）
--   4) 演示种子数据（全部虚构脱敏，仅用于比赛演示与联调）
-- 执行方式：
--   方式一（推荐）：Supabase 控制台 → SQL Editor → New query → 粘贴全部执行
--   方式二：supabase db push（本文件放入项目 supabase/migrations/ 目录）
--   幂等设计：create table if not exists / drop policy if exists /
--             种子数据以 demo-stu1 是否存在为哨兵，可重复执行
-- 文件编码：UTF-8（含中文注释）
-- ============================================================

-- 扩展：用于种子数据密码 sha256 哈希（与 Node 服务端 sha256 十六进制一致）
create extension if not exists pgcrypto;

-- ============================================================
-- 1. schools 学校表（先建：users.school_id 外键依赖）
-- ============================================================
create table if not exists public.schools (
  id            bigint generated by default as identity primary key,
  school_name   text not null,
  region        text,
  student_count int  not null default 0,
  created_time  timestamptz not null default now(),
  constraint uq_schools_name_region unique (school_name, region)
);
create index if not exists idx_schools_region on public.schools(region);
comment on table public.schools is '学校表：学校端/社区端聚合统计的维度表';

-- ============================================================
-- 2. users 用户表
-- ============================================================
create table if not exists public.users (
  id           bigint generated by default as identity primary key,
  username     text not null unique,
  password     text not null,               -- sha256 十六进制哈希（演示级；生产建议接入 Supabase Auth）
  nickname     text not null,
  role         text not null check (role in ('student','parent','school','community')),
  age          int,
  gender       text,
  region       text,
  school_id    bigint references public.schools(id) on delete set null,
  avatar       text,
  created_time timestamptz not null default now()
);
create index if not exists idx_users_role   on public.users(role);
create index if not exists idx_users_school on public.users(school_id);
create index if not exists idx_users_region on public.users(region);
comment on table public.users is '用户表：四角色（学生 student / 家长 parent / 学校 school / 社区 community）';

-- ============================================================
-- 3. ai_personality AI 人格表
-- ============================================================
create table if not exists public.ai_personality (
  id               bigint generated by default as identity primary key,
  user_id          bigint not null references public.users(id) on delete cascade,
  personality_type text not null default '温柔倾听型'
                   check (personality_type in ('温柔倾听型','鼓励成长型','理性分析型')),
  created_time     timestamptz not null default now()
);
create index if not exists idx_ai_personality_user on public.ai_personality(user_id);
comment on table public.ai_personality is 'AI 伙伴人格配置（每位学生一条，可覆盖更新）';

-- ============================================================
-- 4. chat_records AI 聊天记录表
-- ============================================================
create table if not exists public.chat_records (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  message      text not null,               -- 用户消息
  response     text not null,               -- AI 回复
  emotion      text,                        -- 情绪识别输出：压力/焦虑/开心/低落/平静
  risk_level   text not null default 'normal' check (risk_level in ('normal','attention','high')),
  created_time timestamptz not null default now()
);
create index if not exists idx_chat_user on public.chat_records(user_id);
create index if not exists idx_chat_risk on public.chat_records(risk_level);
comment on table public.chat_records is 'AI 聊天记录：家长/学校/社区端均不可见（RLS 无对应策略）';

-- ============================================================
-- 5. assessments 心理测评表
-- ============================================================
create table if not exists public.assessments (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  type         text not null check (type in ('PHQ-9','GAD-7','压力测试','孤独感测试','睡眠测试')),
  score        int  not null,
  level        text,                        -- 分级结论，如 轻度/中度/正常
  result       text,                        -- 结果摘要
  created_time timestamptz not null default now()
);
create index if not exists idx_assessments_user on public.assessments(user_id);
comment on table public.assessments is '心理测评记录：家长可读已绑定孩子的测评摘要（趋势/AI 建议依据）';

-- ============================================================
-- 6. emotion_records 情绪记录表
-- ============================================================
create table if not exists public.emotion_records (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  emotion      text not null check (emotion in ('开心','平静','焦虑','低落','疲惫')),
  pressure     text check (pressure in ('低','中','高')),
  source       text not null default '每日打卡' check (source in ('每日打卡','AI聊天','心理测评')),
  created_time timestamptz not null default now()
);
create index if not exists idx_emotions_user on public.emotion_records(user_id);
comment on table public.emotion_records is '情绪记录：每日打卡/心理测评写入；AI 聊天接口顺带写入（source=AI聊天）';

-- ============================================================
-- 7. family_bindings 家庭绑定表
-- ============================================================
create table if not exists public.family_bindings (
  id           bigint generated by default as identity primary key,
  student_id   bigint not null references public.users(id) on delete cascade,
  parent_id    bigint references public.users(id) on delete cascade,
  invite_code  text not null unique,        -- 8 位邀请码
  status       text not null default 'active' check (status in ('active','expired')),
  created_time timestamptz not null default now()
);
create index if not exists idx_family_student on public.family_bindings(student_id);
create index if not exists idx_family_parent  on public.family_bindings(parent_id);
comment on table public.family_bindings is '家长-学生绑定：家长权限的唯一依据（只读孩子趋势/情绪/AI建议）';

-- ============================================================
-- 8. tree_hole 树洞表
-- ============================================================
create table if not exists public.tree_hole (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  content      text not null,
  emotion      text,
  risk_level   text not null default 'normal' check (risk_level in ('normal','attention','high')),
  created_time timestamptz not null default now()
);
create index if not exists idx_tree_hole_time on public.tree_hole(created_time);
comment on table public.tree_hole is '树洞：匿名展示（对外只经 tree_hole_feed 视图，不含 user_id）';

-- ============================================================
-- 9. user_behavior 用户行为台账表
-- ============================================================
create table if not exists public.user_behavior (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  action       text not null check (action in ('登录','聊天','测评','训练','发布树洞','注册','情绪打卡')),
  created_time timestamptz not null default now()
);
create index if not exists idx_behavior_user on public.user_behavior(user_id);
create index if not exists idx_behavior_time on public.user_behavior(created_time);
comment on table public.user_behavior is '行为台账：需求枚举（登录/聊天/测评/训练/发布树洞）+ 系统补充（注册/情绪打卡）';

-- ============================================================
-- 行级安全 RLS · 四角色策略
-- 设计说明（重要）：
--   * 策略统一以 (auth.uid())::text 与 id/user_id::text 比较 —— 面向「接入
--     Supabase Auth 后 auth.users.id 与 users.id 对齐」的场景；
--   * 心屿 Node 服务端使用 SUPABASE_SERVICE_KEY（service_role）访问，
--     service_role 绕过 RLS，因此同等的权限边界在服务端由路由守卫逐接口实现，
--     与下列策略一一对应（见 docs/权限隔离验证记录.md）；
--   * 学校/社区端不授予任何明细表策略 → 默认拒绝（禁看学生聊天/树洞/明细）；
--     只经下方「安全定义者视图」（默认 security definer，底层 RLS 不阻断聚合）
--     读本校/本区域匿名统计。
-- ============================================================

alter table public.users            enable row level security;
alter table public.schools          enable row level security;
alter table public.ai_personality   enable row level security;
alter table public.chat_records     enable row level security;
alter table public.assessments      enable row level security;
alter table public.emotion_records  enable row level security;
alter table public.family_bindings  enable row level security;
alter table public.tree_hole        enable row level security;
alter table public.user_behavior    enable row level security;

-- 辅助函数：当前登录用户 id（文本），便于策略书写
create or replace function public.current_uid_text() returns text
language sql stable as $$
  select (auth.uid())::text
$$;

-- ---------- users：四角色只能看/改自己的档案 ----------
drop policy if exists users_self_select on public.users;
create policy users_self_select on public.users
  for select to authenticated
  using (id::text = public.current_uid_text());

drop policy if exists users_self_update on public.users;
create policy users_self_update on public.users
  for update to authenticated
  using (id::text = public.current_uid_text());
-- 注：注册/登录为服务端 service_role 行为，不经 RLS

-- ---------- schools：学生/学校看本校，社区看本区域学校 ----------
drop policy if exists schools_visible on public.schools;
create policy schools_visible on public.schools
  for select to authenticated
  using (exists (
    select 1 from public.users u
    where u.id::text = public.current_uid_text()
      and (u.school_id = schools.id or u.region = schools.region)
  ));

-- ---------- ai_personality：学生本人可读写；家长/学校/社区无策略（默认拒绝） ----------
-- 家长可见范围限定为「心理趋势/情绪变化/AI 建议」，AI 人格配置不在开放范围
drop policy if exists ai_personality_self on public.ai_personality;
create policy ai_personality_self on public.ai_personality
  for all to authenticated
  using (user_id::text = public.current_uid_text())
  with check (user_id::text = public.current_uid_text());

-- ---------- chat_records：学生仅本人读写；家长/学校/社区无策略 → 禁看聊天内容 ----------
drop policy if exists chat_records_self_select on public.chat_records;
create policy chat_records_self_select on public.chat_records
  for select to authenticated
  using (user_id::text = public.current_uid_text());

drop policy if exists chat_records_self_insert on public.chat_records;
create policy chat_records_self_insert on public.chat_records
  for insert to authenticated
  with check (user_id::text = public.current_uid_text());

-- ---------- assessments：学生本人读写；家长只读已绑定孩子的测评摘要 ----------
drop policy if exists assessments_self on public.assessments;
create policy assessments_self on public.assessments
  for all to authenticated
  using (user_id::text = public.current_uid_text())
  with check (user_id::text = public.current_uid_text());

drop policy if exists assessments_parent_view on public.assessments;
create policy assessments_parent_view on public.assessments
  for select to authenticated
  using (exists (
    select 1 from public.family_bindings fb
    where fb.parent_id::text = public.current_uid_text()
      and fb.student_id = assessments.user_id
      and fb.status = 'active'
  ));

-- ---------- emotion_records：学生本人读写；家长只读已绑定孩子的情绪记录 ----------
drop policy if exists emotion_records_self on public.emotion_records;
create policy emotion_records_self on public.emotion_records
  for all to authenticated
  using (user_id::text = public.current_uid_text())
  with check (user_id::text = public.current_uid_text());

drop policy if exists emotion_records_parent_view on public.emotion_records;
create policy emotion_records_parent_view on public.emotion_records
  for select to authenticated
  using (exists (
    select 1 from public.family_bindings fb
    where fb.parent_id::text = public.current_uid_text()
      and fb.student_id = emotion_records.user_id
      and fb.status = 'active'
  ));

-- ---------- family_bindings：学生管理自己的绑定；家长只读/绑定自己的记录 ----------
drop policy if exists family_student on public.family_bindings;
create policy family_student on public.family_bindings
  for all to authenticated
  using (student_id::text = public.current_uid_text())
  with check (student_id::text = public.current_uid_text());

drop policy if exists family_parent_view on public.family_bindings;
create policy family_parent_view on public.family_bindings
  for select to authenticated
  using (parent_id::text = public.current_uid_text());

drop policy if exists family_parent_bind on public.family_bindings;
create policy family_parent_bind on public.family_bindings
  for update to authenticated
  using (parent_id::text = public.current_uid_text());

-- ---------- tree_hole：学生本人读写；其他角色无策略（匿名流走视图） ----------
drop policy if exists tree_hole_self on public.tree_hole;
create policy tree_hole_self on public.tree_hole
  for all to authenticated
  using (user_id::text = public.current_uid_text())
  with check (user_id::text = public.current_uid_text());

-- ---------- user_behavior：四角色仅本人 ----------
drop policy if exists behavior_self on public.user_behavior;
create policy behavior_self on public.user_behavior
  for all to authenticated
  using (user_id::text = public.current_uid_text())
  with check (user_id::text = public.current_uid_text());

-- ============================================================
-- 匿名聚合视图（学校端/社区端/树洞匿名流）
-- 说明：
--   * 视图为默认 security definer（所有者 postgres），底层表 RLS 不阻断聚合；
--   * 视图 WHERE 内嵌角色口径（current_uid_text() 定位当前用户）：
--     学校端只能取本校行，社区端只能取本区域行，未登录/无归属 → 0 行；
--   * 服务端 Node（service_role）不依赖本视图，用同样的口径做 JS 聚合
--     （见 server/routes/stats.js），两边结果口径一致；
--   * 视图不含任何学生个体字段（无 user_id/用户名/昵称），满足匿名统计要求。
-- ============================================================

-- ---------- 学校端：本校总览（学生数/测评数/AI 服务次数/风险事件数/测评均值） ----------
create or replace view public.school_cockpit as
select
  s.id                                       as school_id,
  s.school_name,
  s.region,
  count(distinct u.id)                       as student_count,
  count(distinct a.id)                       as assessment_count,
  count(distinct c.id)                       as ai_service_count,
  count(distinct c.id) filter (where c.risk_level in ('attention','high')) as risk_event_count,
  round(coalesce(avg(a.score), 0), 1)        as avg_assessment_score
from public.schools s
left join public.users u        on u.school_id = s.id and u.role = 'student'
left join public.assessments a  on a.user_id = u.id
left join public.chat_records c on c.user_id = u.id
where s.id::text = (
  select uu.school_id::text from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.id, s.school_name, s.region;

-- ---------- 学校端：本校主要压力来源（测评类型 × 均值 × 次数） ----------
create or replace view public.school_pressure_sources as
select
  s.id as school_id,
  a.type,
  round(avg(a.score), 1) as avg_score,
  count(*) as count
from public.schools s
join public.users u        on u.school_id = s.id and u.role = 'student'
join public.assessments a  on a.user_id = u.id
where s.id::text = (
  select uu.school_id::text from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.id, a.type;

-- ---------- 学校端：本校情绪分布 ----------
create or replace view public.school_emotion_distribution as
select
  s.id as school_id,
  e.emotion,
  count(*) as count
from public.schools s
join public.users u       on u.school_id = s.id and u.role = 'student'
join public.emotion_records e on e.user_id = u.id
where s.id::text = (
  select uu.school_id::text from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.id, e.emotion;

-- ---------- 学校端：近 7 日 AI 服务趋势 ----------
create or replace view public.school_trend_7d as
select
  s.id as school_id,
  date_trunc('day', c.created_time)::date as day,
  count(*) as count
from public.schools s
join public.users u        on u.school_id = s.id and u.role = 'student'
join public.chat_records c on c.user_id = u.id
where c.created_time >= now() - interval '7 days'
  and s.id::text = (
    select uu.school_id::text from public.users uu
    where uu.id::text = public.current_uid_text()
  )
group by s.id, date_trunc('day', c.created_time)::date;

-- ---------- 社区端：区域总览（覆盖学校/服务人数/测评数/AI 服务次数） ----------
create or replace view public.community_overview as
select
  s.region,
  count(distinct s.id) as school_count,
  count(distinct u.id) as service_student_count,
  count(distinct a.id) as assessment_count,
  count(distinct c.id) as ai_service_count
from public.schools s
left join public.users u        on u.school_id = s.id and u.role = 'student'
left join public.assessments a  on a.user_id = u.id
left join public.chat_records c on c.user_id = u.id
where s.region = (
  select uu.region from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.region;

-- ---------- 社区端：区域心理需求趋势（测评类型均值） ----------
create or replace view public.community_needs as
select
  s.region,
  a.type,
  round(avg(a.score), 1) as avg_score,
  count(*) as count
from public.schools s
join public.users u       on u.school_id = s.id and u.role = 'student'
join public.assessments a on a.user_id = u.id
where s.region = (
  select uu.region from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.region, a.type;

-- ---------- 社区端：区域情绪分布 ----------
create or replace view public.community_emotion_distribution as
select
  s.region,
  e.emotion,
  count(*) as count
from public.schools s
join public.users u        on u.school_id = s.id and u.role = 'student'
join public.emotion_records e on e.user_id = u.id
where s.region = (
  select uu.region from public.users uu
  where uu.id::text = public.current_uid_text()
)
group by s.region, e.emotion;

-- ---------- 社区端：近 14 日服务趋势（测评/聊天/情绪三类事件） ----------
create or replace view public.community_trend_14d as
select
  s.region,
  date_trunc('day', x.created_time)::date as day,
  count(*) as count
from public.schools s
join public.users u on u.school_id = s.id and u.role = 'student'
join lateral (
  select a.created_time from public.assessments a where a.user_id = u.id
  union all
  select c.created_time from public.chat_records c where c.user_id = u.id
  union all
  select e.created_time from public.emotion_records e where e.user_id = u.id
) x on true
where x.created_time >= now() - interval '14 days'
  and s.region = (
    select uu.region from public.users uu
    where uu.id::text = public.current_uid_text()
  )
group by s.region, date_trunc('day', x.created_time)::date;

-- ---------- 树洞匿名公开流（不含 user_id，不暴露发布者） ----------
create or replace view public.tree_hole_feed as
select id, content, emotion, risk_level, created_time
from public.tree_hole;

-- 视图授权：仅登录角色（authenticated）可读，未登录（anon）不可读
grant select on public.school_cockpit,
                public.school_pressure_sources,
                public.school_emotion_distribution,
                public.school_trend_7d,
                public.community_overview,
                public.community_needs,
                public.community_emotion_distribution,
                public.community_trend_14d,
                public.tree_hole_feed
  to authenticated;

-- ============================================================
-- 演示种子数据（全部虚构脱敏，仅用于比赛演示与本地联调）
-- 统一密码：demo123456（sha256 十六进制，与 Node 服务端一致）
-- 哨兵：demo-stu1 已存在则跳过（幂等）
-- ============================================================
do $$
declare
  v_pwd text := encode(digest('demo123456','sha256'),'hex');
  v_sch_uni bigint;      -- 示范大学（北京市海淀区）
  v_sch_xu  bigint;      -- 阳光社区附小（上海市徐汇区）
  v_stu1 bigint; v_stu2 bigint; v_stu3 bigint; v_user1 bigint;
  v_admin bigint; v_parent bigint; v_com bigint;
  v_seed1 bigint; v_seed2 bigint;
  v_emos text[] := array['焦虑','低落','平静','疲惫','开心','焦虑','平静','低落','疲惫','焦虑','开心','平静','低落','平静'];
  v_pres text[] := array['高','中','低','高','低','中','低','中','中','高','中','低','高','中'];
  i int;
begin
  if exists (select 1 from public.users where username = 'demo-stu1') then
    raise notice '心屿演示种子数据已存在，跳过初始化';
    return;
  end if;

  -- 学校
  insert into public.schools (school_name, region, student_count)
    values ('示范大学','北京市海淀区',4), ('阳光社区附小','上海市徐汇区',2)
    on conflict (school_name, region) do nothing;
  select id into v_sch_uni from public.schools where school_name = '示范大学';
  select id into v_sch_xu  from public.schools where school_name = '阳光社区附小';

  -- 用户（四角色）
  insert into public.users (username,password,nickname,role,age,gender,region,school_id) values
    ('demo-stu1', v_pwd, '小雨同学', 'student', 19, '女', '北京市海淀区', v_sch_uni),
    ('demo-stu2', v_pwd, '晨光同学', 'student', 13, '男', '北京市海淀区', v_sch_uni),
    ('demo-stu3', v_pwd, '晚风同学', 'student', 19, '女', '北京市海淀区', v_sch_uni),
    ('demo-user1', v_pwd, '林间用户', 'student', 20, '女', '', null),
    ('demo-admin1', v_pwd, '张老师', 'school', 32, '女', '北京市海淀区', v_sch_uni),
    ('demo-parent1', v_pwd, '李妈妈', 'parent', 40, '女', '北京市海淀区', null),
    ('demo-com1', v_pwd, '王主任', 'community', 45, '女', '上海市徐汇区', null),
    ('seed-stu1', v_pwd, '小文同学', 'student', 12, '男', '上海市徐汇区', v_sch_xu),
    ('seed-stu2', v_pwd, '小欣同学', 'student', 12, '女', '上海市徐汇区', v_sch_xu);
  select id into v_stu1  from public.users where username = 'demo-stu1';
  select id into v_stu2  from public.users where username = 'demo-stu2';
  select id into v_stu3  from public.users where username = 'demo-stu3';
  select id into v_user1 from public.users where username = 'demo-user1';
  select id into v_admin  from public.users where username = 'demo-admin1';
  select id into v_parent from public.users where username = 'demo-parent1';
  select id into v_com    from public.users where username = 'demo-com1';
  select id into v_seed1  from public.users where username = 'seed-stu1';
  select id into v_seed2  from public.users where username = 'seed-stu2';

  -- AI 人格
  insert into public.ai_personality (user_id, personality_type) values
    (v_stu1, '温柔倾听型'), (v_seed2, '理性分析型');

  -- 测评（覆盖五种类型；分布在不同时间）
  insert into public.assessments (user_id, type, score, level, result, created_time) values
    (v_stu1, 'PHQ-9',      8,  '轻度',     '轻度情绪困扰',     now() - make_interval(days => 21)),
    (v_stu1, 'GAD-7',      10, '中度',     '中度焦虑',         now() - make_interval(days => 18)),
    (v_stu1, '压力测试',   22, '中等压力', '压力水平中等',     now() - make_interval(days => 14)),
    (v_stu1, '孤独感测试', 24, '中度孤独感','需要关注情感陪伴', now() - make_interval(days => 7)),
    (v_stu1, '睡眠测试',   9,  '轻度问题', '轻度睡眠困扰',     now() - make_interval(days => 3)),
    (v_stu1, 'PHQ-9',      6,  '轻度',     '轻度情绪困扰',     now() - make_interval(days => 1)),
    (v_stu2, 'PHQ-9',      3,  '正常',     '状态良好',         now() - make_interval(days => 10)),
    (v_stu2, '压力测试',   12, '较低压力', '压力水平较低',     now() - make_interval(days => 9)),
    (v_stu3, 'GAD-7',      14, '中度',     '中度焦虑',         now() - make_interval(days => 6)),
    (v_seed1,'PHQ-9',      11, '中度',     '中度情绪困扰',     now() - make_interval(days => 8)),
    (v_seed1,'孤独感测试', 18, '中度孤独感','需要关注情感陪伴', now() - make_interval(days => 4)),
    (v_seed2,'压力测试',   15, '中等压力', '压力水平中等',     now() - make_interval(days => 5));

  -- 情绪记录：小雨同学近 14 天每日打卡
  for i in 1..14 loop
    insert into public.emotion_records (user_id, emotion, pressure, source, created_time)
    values (v_stu1, v_emos[i], v_pres[i], '每日打卡',
            now() - make_interval(days => 15 - i) + interval '19 hours');
  end loop;
  insert into public.emotion_records (user_id, emotion, pressure, source, created_time) values
    (v_stu2,  '开心', '低', '每日打卡', now() - make_interval(days => 2) + interval '18 hours'),
    (v_stu3,  '焦虑', '中', '每日打卡', now() - make_interval(days => 1) + interval '20 hours'),
    (v_seed1, '低落', '中', '每日打卡', now() - make_interval(days => 3) + interval '17 hours'),
    (v_seed2, '平静', '低', '每日打卡', now() - make_interval(days => 1) + interval '18 hours'),
    (v_stu1,  '焦虑', '高', 'AI聊天',  now() - make_interval(days => 2) + interval '21 hours');

  -- AI 聊天记录（含记忆演示：小雨同学先提考试压力，后续对话可被 AI 引用）
  insert into public.chat_records (user_id, message, response, emotion, risk_level, created_time) values
    (v_stu1,
     '最近考试压力很大，每天都睡不好',
     '我听到你最近承受着不小的考试压力，还影响了睡眠，这很辛苦。可以试着把复习任务拆小，每天只完成一小块；睡前一小时放下手机，做一组 4-7-8 呼吸。你愿意说说最担心哪一科吗？',
     '压力', 'normal', now() - make_interval(days => 2) + interval '21 hours'),
    (v_stu1,
     '和同桌闹矛盾了，不知道怎么办',
     '人际摩擦是成长里常遇到的事。可以试试「我信息」表达：描述事实+说出感受+提出请求。需要我陪你模拟一下怎么说吗？',
     '低落', 'normal', now() - make_interval(days => 1) + interval '20 hours'),
    (v_seed1,
     '最近好焦虑，感觉什么都做不好',
     '焦虑常常是对「不确定」的过度预警。试试把担心的事分成能控制的和不能控制的，把精力放在前者。你已经愿意说出来，这就是很好的第一步。',
     '焦虑', 'attention', now() - make_interval(days => 1) + interval '22 hours'),
    (v_stu3,
     '今天社团活动挺顺利，开心',
     '真为你开心！这种好的感觉值得被记住——要不要把它写进今天的情绪打卡？',
     '开心', 'normal', now() - make_interval(days => 1) + interval '16 hours');

  -- 树洞（匿名流）
  insert into public.tree_hole (user_id, content, emotion, risk_level, created_time) values
    (v_stu1,  '期中考试要来了，越想越睡不着，有没有同学也是这样？', '焦虑', 'normal', now() - make_interval(days => 2) + interval '22 hours'),
    (v_seed2, '今天帮同学讲了一道题，他说谢谢，还挺开心的',           '开心', 'normal', now() - make_interval(days => 1) + interval '18 hours');

  -- 家庭绑定：李妈妈 ↔ 小雨同学（预绑定）；另留一条未绑定邀请码演示绑定流程
  insert into public.family_bindings (student_id, parent_id, invite_code, status, created_time) values
    (v_stu1, v_parent, 'XY20260815', 'active', now() - make_interval(days => 5)),
    (v_seed1, null,     'XH20260001', 'active', now() - make_interval(days => 2));

  -- 行为台账
  insert into public.user_behavior (user_id, action, created_time) values
    (v_stu1, '注册',     now() - make_interval(days => 21)),
    (v_stu1, '登录',     now() - make_interval(days => 1) + interval '8 hours'),
    (v_stu1, '聊天',     now() - make_interval(days => 1) + interval '20 hours'),
    (v_stu1, '测评',     now() - make_interval(days => 1) + interval '21 hours'),
    (v_stu1, '情绪打卡', now() - interval '8 hours'),
    (v_stu1, '训练',     now() - make_interval(days => 2) + interval '10 hours'),
    (v_parent, '注册',   now() - make_interval(days => 4)),
    (v_admin,  '注册',   now() - make_interval(days => 4)),
    (v_com,    '注册',   now() - make_interval(days => 4)),
    (v_seed2,  '发布树洞', now() - make_interval(days => 1) + interval '18 hours');

  raise notice '心屿演示种子数据初始化完成（9 账号，密码均为 demo123456）';
end $$;

-- ============================================================
-- 完。验证清单：
--   select count(*) from public.users;                     -- 9
--   select * from public.school_cockpit;                   -- 学校端聚合口径
--   select * from public.community_overview;               -- 社区端聚合口径
-- ============================================================
